### ISSUE TITLE
Allow overriding the diagnostic settings the way you can with `vim.diagnostic.set()`

### ISSUE THREAD

**Issue by titaniumtraveler** [ravibrock/spellwarn.nvim#6]
The motivating example is that I like having `virtualtext = true` for lsp diagnostics, but for spelling mistakes I prefer to just have different highlighting. (i. e. the misspelled word being underscored)

So it would be cool if there were a config option to just pass opts directly to the `vim.diagnostic.set()` as described in `:h vim.diagnostic.config()`:
> For example, if a user enables virtual text globally with
> vim.diagnostic.config({ virtual_text = true })
>
> and a diagnostic producer sets diagnostics with
> vim.diagnostic.set(ns, 0, diagnostics, { virtual_text = false })

I know you can set that on a per-namespace basis. (Just learned that lol)
But I think having a config option would still be more convenient.

Edit:
My stopgap for now is
```lua
require "spellwarn".setup()

local ns = vim.api.nvim_get_namespaces()["Spellwarn"]
vim.diagnostic.config({ virtual_text = false }, ns)
```

**Comment by ravibrock** [comment]
Perhaps I'm misunderstanding something, but what would be the point of using Spellwarn if it doesn't display diagnostics? You can already jump between spelling mistakes with `[s` and `]s`, and there are plugins like [vim-spellcheck](https://github.com/inkarkat/vim-SpellCheck) that allow you to populate the quickfix list with errors if you want them to all be in one place.

**Comment by titaniumtraveler** [comment]
> Perhaps I'm misunderstanding something, but what would be the point of using Spellwarn if it doesn't display diagnostics?

I mean I still get the signs in the sign column. But in the end it doesn't really matter.
Being able to override the diagnostic config would be helpful for any user IMO.

**Comment by ravibrock** [comment]
> I mean I still get the signs in the sign column.

Ah, fair enough. I forgot that you can display diagnostics in the sign column. I'll add that diagnostic config option when I get the chance.
