### ISSUE TITLE
Detect when zg is used to add to spell dictionary

### ISSUE THREAD

**Issue by cavanaug** [ravibrock/spellwarn.nvim#8]
Might be able to use the FileAppendCmd event but Im not sure of the implications with many buffers open.   Perhaps you can detect which file was appended to.  There definitely is an event somewhere because it is shown in noice.

**Comment by ravibrock** [comment]
Hi, sorry, forgot to respond to this. I believe it should automatically adjust to the new word being marked as correct once it updates diagnostics the next time (on the `CursorHold`, `TextChanged`, etc. events). I tested just now and it seems to have worked that way; is that not the case for you?

**Comment by cavanaug** [comment]
CursorHold is like 4 secs which makes it not so useful.   I wanted immediate feedback in the ui (no longer underlined for example) to know that my action was registered.   Im not sure what Noice is triggering off of, but that is likely a good source because it shows immediately that spelling was updated.

**Comment by ravibrock** [comment]
This is low priority for me, sorry--I see what you're saying, but I think that the case of marking words correct is rare enough that a worst-case delay of 4 seconds is acceptable for the moment. I'm also not sure how edge cases would work with related commands (enter `:h zg` and scroll down to see `zG`,  `zug`, etc.).
